### PR TITLE
Testing ComPR Open Source

### PR DESCRIPTION
**Pull request by scherniavsky**
Testing ComPR Open Source

### CODE REVIEW

**Comment by scherniavsky** [comment]
test

**Comment by scherniavsky** [comment]
:+1:

**Comment by scherniavsky** [comment]
:+1:

**Comment by scherniavsky** [comment]
:+1:

**Comment by scherniavsky** [comment]
:+1:

**Comment by scherniavsky** [comment]
@zalando/machinery test

**Comment by kanistha** [comment]
👍

**Comment by kanistha** [comment]
👍

**Comment by tkrop** [comment]
:+1:

**Pull request merged**
